### ISSUE TITLE
Find that pid

### ISSUE THREAD

**Issue by wernerlaude** [wilsonsilva/process_exists#1]
Hi.. 
just found your gem, looks useful to me. Thanks.
What I am busy with is:
In Rails 4 I start an external program (OpenFoam) via command line. It will run for quite some time and I need the info when its finished to get "workflow" to set the state on finished..  
So my idea is to grap the pid and check..I know the name of the pid..
How to get it together ?
pid = 12
pid_exists = Process.exists?(pid)
Is your gem also check a name?

Thanks  Werner

**Comment by wilsonsilva** [comment]
It is not something supported at the moment, but I will add it in the next release. Meanwhile you can issue a system command and check its existance:

``` ruby
foam_processes = `ps cax | grep foam`
foam_running = !foam_processes.empty?
```

Please keep in mind that simply parsing the output of ps is not simply matching on processes, but also the arguments passed to that program.

Alternatively, when you start a program via the command line you can get the pid right away using something around the lines of:

``` ruby
foam_pid = `foam & echo $!`
```

Once you know the pid you can probably use [waitpid](http://ruby-doc.org/core-2.2.3/Process.html#method-c-waitpid) which waits for a child process to exit.

**Comment by wernerlaude** [comment]
Thanks..
I will test that..

Greetings from Munich
